sudo: false
dist: trusty
language: node_js
stages:
  - test
  - publish
git:
  depth: 3
node_js:
  - "8"
install:
  - npm install -g gulp-cli
  - npm install
  - npm install ionicons@2.0.1
cache:
  directories:
    - ~/.npm
    - node_modules
jobs:
  include:
    - stage: test
      script: gulp build
    - stage: publish
      script:
        - gulp build
        - cp readme.md dist
        - cp .npmrc dist
        - cp package.json dist
        - cd dist && npm publish
      on:
        tags: true
      if: $TRAVIS_TAG ~= /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
