sudo: false
dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "8"
install:
  - npm install -g gulp-cli
  - npm install
cache:
  directories:
    - ~/.npm
    - node_modules
jobs:
  include:
    - stage: test
      script: gulp build
    - stage: publish
      script:
        - cp package.json dist
        - cd dist && npm publish
      on:
        tags: true
        condition: $TRAVIS_TAG ~= /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
